name: CMake

on: [ push ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -G "CodeBlocks - Unix Makefiles" $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Upload the Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{github.workspace}}/build

  test:
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        label: [ identifiers_counter, lexical_analyzer, recursive_descent_parser ]
        experimental: [ false ]
        include:
          - label: recursive_descent_parser
            experimental: true

    steps:
      - uses: actions/checkout@v2

      - name: Download the Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ${{github.workspace}}/build

      - name: Run CTest
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: chmod u+x ./test_${{matrix.label}} && ctest -C $BUILD_TYPE --extra-verbose -L ${{matrix.label}}
